apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-hostpath
  labels:
    app: wordpress-hostpath
    tier: mysql-hostpath
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-hostpath
      tier: mysql-hostpath
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-hostpath
        tier: mysql-hostpath
    spec:
      containers:
        - image: mysql:5.6
          name: mysql-hostpath
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: changeme
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          hostPath:
            path: /tmp/mysql
