apiVersion: batch/v1
kind: Job
metadata:
  name: job-test
  annotations:
    io.kubernetes-network.region-id: "region-id-test"
    io.kubernetes-network.subnet-id: "subnet-id-test"
    io.kubernetes-network.subnetgatewayaddr: "subnetgatewayaddr-test"
    io.kubernetes-webhook-server.cluster-id: "cluster-id-test"
    io.kubernetes-network.subnetcidr: "subnetcidr"
spec:
  template:
    metadata:
      name: job-test
    spec:
      restartPolicy: Never
      containers:
        - name: job-test
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            - "bin/sh"
            - "-c"
            - "for i in 9 8 7 6 5 4 3 2 1; do echo $i; done"