apiVersion: v1
kind: Service
metadata:
  name: mysql-statefulset
  labels:
    app: mysql-statefulset
spec:
  ports:
    - port: 3306
      name: mysql-statefulset
  clusterIP: None
  selector:
    app: mysql-statefulset
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  labels:
    app: mysql-statefulset
  annotations:
    xxx: xxxx
spec:
  serviceName: mysql-statefulset
  replicas: 2
  selector:
    matchLabels:
      app: mysql-statefulset
  template:
    metadata:
      labels:
        app: mysql-statefulset
      annotations:
        io.kubernetes-webhook-server.cluster-id: "cluster-id-test"
        io.kubernetes-network.region-id: "region-id-test"
        io.kubernetes-network.subnet-id: "subnet-id-test"
        io.kubernetes-network.subnetgatewayaddr: "subnetgatewayaddr-test"
        io.kubernetes-network.subnetcidr: "subnetcidr"
    spec:
      containers:
        - image: mysql:5.6
          name: mysql-statefulset
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: changeme
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          hostPath:
            path: /tmp/mysql
