apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-webhook
  namespace: kube-webhook
  labels:
    app: kube-webhook
spec:
  selector:
    matchLabels:
      app: kube-webhook
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-webhook
    spec:
      serviceAccount: webhook-server-sa
      hostNetwork: true
      containers:
        - name: kube-webhook
          image: kube-webhook:latest
          imagePullPolicy: IfNotPresent
          args:
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -port=9443
            - -alsologtostderr
            - -v=4
          livenessProbe:
            httpGet:
              path: /health
              port: 9080
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /health
              port: 9080
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 2
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
          env:
            - name: RESOURCE_ADDRESS
              value: "127.0.0.1:9999"
      volumes:
        - name: webhook-certs
          secret:
            secretName: kube-webhook-certs
