---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-server-sa
  namespace: kube-webhook

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webhook-server
rules:
  - apiGroups: ["apps/v1", "apps/v1beta1", "apps/v1beta2", "extensions/v1beta1"]
    resources: ["deployments"]
    verbs: ["get", "list"]
  - apiGroups: ["apps/v1"]
    resources: ["statefulsets"]
    verbs: ["get", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webhook-server-role
subjects:
  - kind: ServiceAccount
    name: webhook-server-sa
    namespace: kube-webhook
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""