apiVersion: v1
kind: Service
metadata:
  name: kube-webhook-svc
  namespace: kube-webhook
  labels:
    app: kube-webhook
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    app: kube-webhook
